### ISSUE TITLE
Fatal Python error: init_fs_encoding: failed to get the python codec of the filesystem encoding

### ISSUE THREAD

**Issue by mrjaksauce** [kakaroto/R20Converter#76] opened 2021-06-05 10:16 UTC
![image](https://user-images.githubusercontent.com/68178310/120888287-8a4bc380-c64b-11eb-8c36-d88a14c87698.png)

**Comment by kakaroto** [comment] 2021-06-05 10:20
Where did you get R20Converter from? Because that is not the latest version of the software.

**Comment by mrjaksauce** [comment] 2021-06-06 00:27
I've had it for some time in my downloads and I went back to use it. 
![image](https://user-images.githubusercontent.com/68178310/120908825-8b6c0780-c6c2-11eb-893c-8268161ef34c.png)

**Comment by kakaroto** [comment] 2021-06-06 01:46
Ah ok.
I'm not sure about the issue you're having. I do remember something like that happening in some rare cases which I can't remember the cause to, but that has been fixed a while ago (maybe about a year ago, so that checks out with how old your version is).
If you can't sub to patreon again to get the latest release, I'd recommend trying it maybe in a regular terminal (not powershell) and if you use a non-english version of Windows, trying it on a Virtual machine with standard English Windows installed. As I think the issue might either be related to the terminal used, or to the language encoding of the system.
Closing the issue as it's for such an old version of R20Converter, that there's nothing for me to do unless you can confirm it still happens in the latest release. Feel free to keep replying to the closed issue if you still need more help resolving it for you specifically.
Thanks.

**Closed by kakaroto** 2021-06-06 01:46 UTC
