### ISSUE TITLE
Persistent error with multiple exports

### ISSUE THREAD

**Issue by mjsohm** [kakaroto/R20Converter#91] opened 2024-10-28 11:41 UTC
Hi there,

This happened with two recent exports from Roll20 in Oct 2024.  Princes of the Apocalypse and Dungeon of the Mad Mage. New install of the converter. Windows 11.  Multiple attempts. Re-exported to new .zip file with same result. Creates the world, then hangs at the end.

Error converting campaign with R20Converter v0.13.3:
Traceback (most recent call last):
File "src\GUI.py", line 183, in startConversion
File "src\R20Converter.py", line 223, in convert
File "src\entities\scenes.py", line 21, in __init__
File "src\entities\scenes.py", line 32, in genEntities
File "src\entities\scenes.py", line 32, in
File "src\entities\scenes.py", line 630, in __init__
KeyError: 'showlighting'

Please contact the author with the log of the error from the console window

**Comment by kakaroto** [comment] 2024-10-28 19:39
Hi,
R20Converter doesn't currently support Roll20's Jumpgate beta feature, as it completely changed the way that campaign's data is stored and used.
Create a new campaign but without using jumpgate and the export/convert should work properly.

Closing this issue as it's a duplicate of https://github.com/kakaroto/R20Converter/issues/89

**Closed by kakaroto** 2024-10-28 19:39 UTC
